
# получение объявлений
GET http://localhost:8000/api/advertisements/
Content-Type: application/json

###

# создание объявления
POST http://localhost:8000/api/advertisements/
Content-Type: application/json
Authorization: Token f2a91b70df6f7a9825ea18dc38cba8db33499303
#Authorization: Token 98fc142d09eadfc183a842e262ce550110ff27d1


{
  "title": "полка",
  "description": "пластик"
}

###

# попытка поменять объявление
PATCH http://localhost:8000/api/advertisements/2/
Content-Type: application/json
#Authorization: Token f2a91b70df6f7a9825ea18dc38cba8db33499303
Authorization: Token 98fc142d09eadfc183a842e262ce550110ff27d1

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET http://localhost:8000/api/advertisements/?creator=2
Content-Type: application/json

###

###

# фильтрация по дате
GET http://localhost:8000/api/advertisements/?created_at_before=2021-11-27
Content-Type: application/json
